---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
    run_list:
    - recipe[apt]
  - name: ubuntu-12.04
    run_list:
    - recipe[apt]
  - name: centos-6.5
    run_list:
    - recipe[yum]

suites:
  - name: default
    driver:
      vm_hostname: rackspace-monitoring-vm
    run_list:
      - recipe[rackspace_monitoring::default]
    exclude: ['ubuntu-12.04', 'centos-6.5']
    attributes:
      monitoring:
        enabled: true
        agent:
          token: 0000000000000000000000000000000000000000000000000000000000000000.000000
      rackspace:
        cloud_credentials:
          username: ChangeMe
          api_key: 00000000000000000000000000000000
