---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[rackspace_monitoring]
    attributes:
      monitoring:
        enabled: true
        agent:
          token: 0000000000000000000000000000000000000000000000000000000000000000.000000
      rackspace:
        cloud_credentials:
          username: ChangeMe
          api_key: 00000000000000000000000000000000
