inherit_from: .rubocop_todo.yml

AllCops:
  Include:
    - '**/Berksfile'
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/Thorfile'
    - '**/Guardfile'
  Exclude:
    - vendor/**/*

LineLength:
  Enabled: false
